create table "AccountGroup"
(
    id                   integer generated by default as identity
        constraint account_group_id_primary
            primary key,
    "AccountType"        varchar(100) not null,
    "AccountDescription" varchar      not null,
    "CreatedDate"        timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"          integer,
    "IsActive"           boolean,
    "ModifiedDate"       timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "AccountGroup"
    owner to postgres;

create table "AccountStatus"
(
    id                      integer generated by default as identity
        constraint account_status_id_primary
            primary key,
    "AccountCreatedDate"    timestamp with time zone default CURRENT_TIMESTAMP,
    "AccountExpirationDate" date,
    "CreatedDate"           timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"             integer,
    "IsActive"              boolean,
    "ModifiedDate"          timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "AccountStatus"
    owner to postgres;

create table "ClinicList"
(
    id             integer generated by default as identity
        constraint "ClinicList_pkey"
            primary key,
    "ClinicName"   varchar not null,
    "Description"  varchar not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer,
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "ClinicList"
    owner to postgres;

create table "IdType"
(
    id              integer generated by default as identity
        constraint idtype_id_primary
            primary key,
    "IdType"        varchar(255) not null,
    "IdDescription" varchar(255) not null,
    "CreatedDate"   timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"     integer,
    "IsActive"      boolean,
    "ModifiedDate"  timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "IdType"
    owner to postgres;

create table "PhoneNumberType"
(
    id             integer generated by default as identity
        constraint phone_number_type_id_primary
            primary key,
    "PhoneType"    varchar(255) not null,
    "Description"  varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer,
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "PhoneNumberType"
    owner to postgres;

create table "AccountInformation"
(
    id                  integer generated by default as identity
        constraint accountinformation_id_primary
            primary key,
    "TitleId"           integer,
    "IdNumber"          varchar(255),
    "IdTypeId"          integer
        constraint accountinformation_id_type_foreign
            references "IdType",
    "Email"             varchar(255),
    "PhoneNumberTypeId" integer
        constraint accountinformation_phone_number_foreign
            references "PhoneNumberType",
    "PhoneNumber"       integer,
    "RegionId"          integer,
    "CountryId"         integer,
    "SubCityId"         integer,
    "ZoneId"            integer,
    "WoredaId"          integer not null,
    "Kebele"            varchar(255),
    "HouseNumber"       varchar(255),
    "CreatedDate"       timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"         integer,
    "ModifiedDate"      timestamp with time zone default CURRENT_TIMESTAMP,
    "GenderId"          integer
);

alter table "AccountInformation"
    owner to postgres;

create table "Accounts"
(
    id                     integer generated by default as identity
        constraint accounts_id_primary
            primary key,
    "FirstName"            varchar(255),
    "MiddleName"           varchar(255),
    "LastName"             varchar(255),
    "AccountGroupId"       integer
        constraint accounts_accountgruop_id_foreign
            references "AccountGroup",
    "AccountStatusId"      integer
        constraint accounts_accountstatus_id_foreign
            references "AccountStatus",
    "UserName"             varchar(255),
    "Password"             varchar(255),
    "CreatedDate"          timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"            integer
        constraint accounts_accounts_id_fk
            references "Accounts",
    "ModifiedDate"         timestamp with time zone default CURRENT_TIMESTAMP,
    "AccountInformationId" integer
        constraint "AccountInformation_accountstatus_id_foreign"
            references "AccountInformation"
);

alter table "Accounts"
    owner to postgres;

create unique index accounts_username_uindex
    on "Accounts" ("UserName");

create table "Appointments"
(
    id             integer generated by default as identity
        constraint "Appointments_pkey"
            primary key,
    "Appointment"  date not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "Appointments_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Appointments"
    owner to postgres;

create table "Country"
(
    id             integer generated by default as identity
        constraint country_id_primary
            primary key,
    "CCA2"         varchar(255) not null,
    "Name"         varchar(255) not null,
    "CCA3"         varchar(255) not null,
    "Nationality"  varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "Country_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Country"
    owner to postgres;

create table "DeathCertification"
(
    id                    integer generated by default as identity
        constraint "DeathCertification_pkey"
            primary key,
    "PatientId"           integer      not null,
    "DeathDatetime"       date         not null,
    "DeathLocation"       varchar(255) not null,
    "BriefMedicalHistory" varchar(255) not null,
    "CreatedDate"         timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"           integer
        constraint "DeathCertification_accounts_id_foreign"
            references "Accounts",
    "IsActive"            boolean,
    "ModifiedDate"        timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "DeathCertification"
    owner to postgres;

create table "DiagnosisList"
(
    id             integer generated by default as identity
        constraint "DiagnosisList_pkey"
            primary key,
    "Diagnosis"    varchar(255) not null,
    "Code"         varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "DiagnosisList_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "DiagnosisList"
    owner to postgres;

create table "Gender"
(
    id             integer generated by default as identity
        constraint gender_id_primary
            primary key,
    "Type"         varchar(255) not null,
    "Description"  varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "Gender_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Gender"
    owner to postgres;

alter table "AccountInformation"
    add constraint accountinformation_gender_id_fk
        foreign key ("GenderId") references "Gender";

create table "IntraReferral"
(
    id              integer generated by default as identity
        constraint "IntraReferral_pkey"
            primary key,
    "PatientId"     integer not null,
    "Clinic"        integer not null
        constraint "IntraReferral_ClinicId_id_foreign"
            references "ClinicList",
    "ClinicReferTo" integer not null
        constraint "IntraReferral_ClinicReferTo_id_foreign"
            references "ClinicList",
    "Note"          varchar not null,
    "CreatedDate"   timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"     integer
        constraint "IntraReferral_accounts_id_foreign"
            references "Accounts",
    "IsActive"      boolean,
    "ModifiedDate"  timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "IntraReferral"
    owner to postgres;

create table "IsExpire"
(
    id             integer generated by default as identity
        constraint "IsExpire_pkey"
            primary key,
    "IsExpire"     boolean      not null,
    "Remark"       varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "IsExpire_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "IsExpire"
    owner to postgres;

create table "LabDepartment"
(
    id             integer generated by default as identity
        constraint "LabDepartment_pkey"
            primary key,
    name           varchar(255) not null,
    abbreviation   varchar(255) not null,
    remark         varchar      not null,
    "createdDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "createdBy"    integer
        constraint "LabDepartment_accounts_id_foreign"
            references "Accounts",
    "isActive"     boolean,
    "modifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "LabDepartment"
    owner to postgres;

create table "LabTransferStatus"
(
    id              integer generated by default as identity
        constraint "LabTransfer_pkey"
            primary key,
    "isTransfered"  boolean not null,
    "Remark"        varchar not null,
    "TransferredBy" integer
        constraint "PaymentStatus_accounts_id_foreign"
            references "Accounts",
    "CreatedDate"   timestamp with time zone default CURRENT_TIMESTAMP,
    "ModifiedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "IsActive"      boolean
);

alter table "LabTransferStatus"
    owner to postgres;

create table "MaritalStatus"
(
    id             integer generated by default as identity
        constraint "MaritalStatus_id_primary"
            primary key,
    "Status"       varchar(255) not null,
    "Description"  varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "MaritalStatus_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "MaritalStatus"
    owner to postgres;

create table "Occupations"
(
    id                integer generated by default as identity
        constraint occupations_id_primary
            primary key,
    "Occupation_List" varchar(255) not null,
    "CreatedDate"     timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"       integer
        constraint "Occupations_accounts_id_foreign"
            references "Accounts",
    "IsActive"        boolean,
    "ModifiedDate"    timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Occupations"
    owner to postgres;

create table "PatientHistory"
(
    id             integer generated by default as identity
        constraint "PatientHistory_pkey"
            primary key,
    "HistoryNote"  varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "PatientHistory_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "PatientHistory"
    owner to postgres;

create table "PatientManagement"
(
    id             integer generated by default as identity
        constraint "PatientManagement_pkey"
            primary key,
    "Management"   varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "PatientManagement_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "PatientManagement"
    owner to postgres;

create table "PatientProgress"
(
    id             integer generated by default as identity
        constraint "PatientProgress_pkey"
            primary key,
    "Progress"     varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "PatientProgress_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "PatientProgress"
    owner to postgres;

create table "PatientStatus"
(
    id             integer generated by default as identity
        constraint "PatientStatus_id_primary"
            primary key,
    "Status"       varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "PatientStatus_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "PatientStatus"
    owner to postgres;

create table "PhysicalExamination"
(
    id                  integer generated by default as identity
        constraint "PhysicalExamination_pkey"
            primary key,
    "GeneralAppearance" varchar(255) not null,
    "HEENT"             varchar(255) not null,
    "RespiratorySystem" varchar(255) not null,
    "CVS"               varchar(255) not null,
    "Abdomen"           varchar(255) not null,
    "GUS"               varchar(255) not null,
    "MSS"               varchar(255) not null,
    "Integumentary"     varchar(255) not null,
    "CNS"               varchar(255) not null,
    "Obstetrics"        varchar(255) not null,
    "Gynecological"     varchar(255) not null,
    "Neonatal"          varchar(255) not null,
    "LGS"               varchar(255) not null,
    "Weight"            varchar      not null,
    "Height"            varchar      not null,
    "CreatedDate"       timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"         integer
        constraint "PhysicalExamination_accounts_id_foreign"
            references "Accounts",
    "IsActive"          boolean,
    "ModifiedDate"      timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "PhysicalExamination"
    owner to postgres;

create table "RadDepartment"
(
    id             integer generated by default as identity
        constraint "RadDepartment_pkey"
            primary key,
    "Name"         varchar(255) not null,
    "Abbreviation" varchar(255) not null,
    "Remark"       varchar      not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "RadDepartment_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "RadDepartment"
    owner to postgres;

create table "RadRequest"
(
    id                 integer generated by default as identity
        constraint "RadRequest_pkey"
            primary key,
    "RequestName"      varchar(255)     not null,
    "Abbreviation"     varchar(255)     not null,
    "ShortDescription" varchar(255)     not null,
    "Price"            double precision not null,
    "RadDepartmentId"  integer          not null
        constraint "RadRequest_department_id_foreign"
            references "RadDepartment",
    "CreatedDate"      timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"        integer
        constraint "RadRequest_accounts_id_foreign"
            references "Accounts",
    "IsActive"         boolean,
    "ModifiedDate"     timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "RadRequest"
    owner to postgres;

create table "RadTransferStatus"
(
    id              integer generated by default as identity
        constraint "RadTransfer_pkey"
            primary key,
    "isTransfered"  boolean not null,
    "Remark"        varchar not null,
    "TransferredBy" integer,
    "CreatedDate"   timestamp with time zone default CURRENT_TIMESTAMP,
    "IsActive"      boolean,
    "ModifiedDate"  timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "RadTransferStatus"
    owner to postgres;

create table "Region"
(
    id             integer generated by default as identity
        constraint region_id_primary
            primary key,
    "RegionName"   varchar(255) not null,
    "CountryId"    integer      not null
        constraint region_country_id_foreign
            references "Country",
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "Region_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Region"
    owner to postgres;

create table "Relationship"
(
    id                 integer generated by default as identity
        constraint "Relationship_id_primary"
            primary key,
    "RelationshipType" varchar(100) not null,
    "Description"      varchar      not null,
    "CreatedDate"      timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"        integer,
    "IsActive"         boolean,
    "ModifiedDate"     timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Relationship"
    owner to postgres;

create table "PatientEmergencyContact"
(
    id               integer generated by default as identity
        constraint "PatientEmergencyContact_id_primary"
            primary key,
    "FirstName"      varchar(255) not null,
    "MiddleName"     varchar(255) not null,
    "LastName"       varchar(255) not null,
    "GenderId"       integer      not null
        constraint "PatientEmergencyContact_gender_foreign"
            references "Gender",
    "RelationshipId" integer      not null
        constraint "PatientEmergencyContact_Relationship_foreign"
            references "Relationship",
    "PhoneNumber"    varchar      not null,
    "CreatedDate"    timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"      integer
        constraint "PatientEmergencyContact_accounts_id_foreign"
            references "Accounts",
    "ModifiedDate"   timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "PatientEmergencyContact"
    owner to postgres;

create table "SickLeave"
(
    id               integer generated by default as identity
        constraint "SickLeave_pkey"
            primary key,
    "PatientId"      integer      not null,
    "DiagnosisId"    integer,
    "Recommendation" varchar(255) not null,
    "TotalLeaveDays" integer      not null,
    "CreatedDate"    timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"      integer
        constraint "SickLeave_accounts_id_foreign"
            references "Accounts",
    "IsActive"       boolean,
    "ModifiedDate"   timestamp with time zone default CURRENT_TIMESTAMP,
    "Clinic"         integer
        constraint sickleave_cliniclist_id_fk
            references "ClinicList",
    "Diagnosis"      varchar
);

alter table "SickLeave"
    owner to postgres;

create table "ItemStatus"
(
    id             integer generated by default as identity
        constraint "Status_pkey"
            primary key,
    status         boolean      not null,
    remark         varchar(255) not null,
    "createdDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "createdBy"    integer
        constraint "Status_accounts_id_foreign"
            references "Accounts",
    "isActive"     boolean,
    "modifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "ItemStatus"
    owner to postgres;

create table "LabPanels"
(
    id                   integer generated by default as identity
        constraint "LabPanels_pkey"
            primary key,
    "panelsAbbreviation" varchar(255)     not null,
    "shortDescription"   varchar(255)     not null,
    price                double precision not null,
    "departmentId"       integer          not null
        constraint panels_department_id_foreign
            references "LabDepartment",
    "statusId"           integer          not null
        constraint panels_status_id_foreign
            references "ItemStatus",
    "createdDate"        timestamp with time zone default CURRENT_TIMESTAMP,
    "createdBy"          integer
        constraint "LabPanels_accounts_id_foreign"
            references "Accounts",
    "isActive"           boolean,
    "modifiedDate"       timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "LabPanels"
    owner to postgres;

create table "SubCity"
(
    id             integer generated by default as identity
        constraint "subCity_id_primary"
            primary key,
    "FullName"     varchar(255) not null,
    "RegionId"     integer      not null
        constraint subcity_region_id_foreign
            references "Region",
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "SubCity_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "SubCity"
    owner to postgres;

create table "Title"
(
    id             integer generated by default as identity
        constraint title_id_primary
            primary key,
    "Title"        varchar(255) not null,
    "Abbreviation" varchar(255) not null,
    "Description"  varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "Title_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Title"
    owner to postgres;

alter table "AccountInformation"
    add constraint accountinformation_title_id_foreign
        foreign key ("TitleId") references "Title";

create table "UnitOfMeasurements"
(
    id             integer generated by default as identity
        constraint "UnitOfMeasurements_pkey"
            primary key,
    name           varchar(255) not null,
    symbols        varchar(255) not null,
    "createdDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "createdBy"    integer
        constraint "UnitOfMeasurements_accounts_id_foreign"
            references "Accounts",
    "isActive"     boolean,
    "modifiedDate" timestamp with time zone default CURRENT_TIMESTAMP,
    description    varchar
);

alter table "UnitOfMeasurements"
    owner to postgres;

create table "LabTests"
(
    id                     integer generated by default as identity
        constraint "LabTests_pkey"
            primary key,
    "testName"             varchar(255) not null,
    abbreviation           varchar(255) not null,
    "shortDescription"     varchar(255) not null,
    "unitOfMeasurementsId" integer      not null
        constraint tests_unit_of_measurement_id_foreign
            references "UnitOfMeasurements",
    "createdDate"          timestamp with time zone default CURRENT_TIMESTAMP,
    "createdBy"            integer
        constraint "LabTests_accounts_id_foreign"
            references "Accounts",
    "isActive"             boolean,
    "modifiedDate"         timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "LabTests"
    owner to postgres;

create table "LabPanelTest"
(
    id             integer generated by default as identity
        constraint "LabPanelTest_pkey"
            primary key,
    "panelId"      integer not null
        constraint panel_test_panel_id_foreign
            references "LabPanels",
    "testId"       integer not null
        constraint panel_test_test_id_foreign
            references "LabTests",
    "createdDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "createdBy"    integer
        constraint "LabPanelTest_accounts_id_foreign"
            references "Accounts",
    "isActive"     boolean,
    "modifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "LabPanelTest"
    owner to postgres;

create table "VitalSigns"
(
    id                                        integer generated by default as identity
        constraint "VitalSigns_pkey"
            primary key,
    "Blood Pressure(BP)"                      varchar not null,
    "Pulse Rate(PR)"                          varchar not null,
    "Respiration Rate(RR)"                    varchar not null,
    "Saturation of Oxygen in the Blood(SPO2)" varchar not null,
    "Body Temperature(BT)"                    varchar not null,
    "CreatedDate"                             timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"                               integer
        constraint "VitalSigns_accounts_id_foreign"
            references "Accounts",
    "IsActive"                                boolean,
    "ModifiedDate"                            timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "VitalSigns"
    owner to postgres;

create table "Woreda"
(
    id             integer generated by default as identity
        constraint woreda_id_primary
            primary key,
    "WoredaName"   varchar(255),
    "SubCityId"    integer
        constraint "woreda_subCity_id_foreign"
            references "SubCity",
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "Woreda_accounts_id_foreign"
            references "Accounts",
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Woreda"
    owner to postgres;

create table "Zone"
(
    id             integer generated by default as identity
        constraint zone_id_primary
            primary key,
    "ZoneName"     varchar(255) not null,
    "RegionId"     integer      not null
        constraint zone_region_id_foreign
            references "Region",
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "Zone_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Zone"
    owner to postgres;

create table "PatientList"
(
    id                          integer generated by default as identity
        constraint patient_id_primary
            primary key,
    "PreviousMRN"               varchar      not null,
    "FirstName"                 varchar(255) not null,
    "MiddleName"                varchar(255) not null,
    "LastName"                  varchar(255) not null,
    "DateOfBirth"               varchar      not null,
    "PhoneNumber"               varchar      not null,
    "Email"                     varchar(255) not null,
    "Postal"                    varchar(255) not null,
    "GenderId"                  integer      not null
        constraint patient_gender_foreign
            references "Gender",
    "MaritalStatusId"           integer      not null
        constraint "patient_maritalStatus_foreign"
            references "MaritalStatus",
    "OccupationId"              integer      not null
        constraint patient_occupation_foreign
            references "Occupations",
    "CountryId"                 integer      not null
        constraint patient_country_foreign
            references "Country",
    "RegionId"                  integer      not null
        constraint patient_region_foreign
            references "Region",
    "SubCityId"                 integer      not null
        constraint patient_subcity_foreign
            references "SubCity",
    "WoredaId"                  integer      not null
        constraint patient_woreda_foreign
            references "Woreda",
    "ZoneId"                    integer
        constraint patient_zone_foreign
            references "Zone",
    "Kebele"                    varchar(255) not null,
    "HouseNumber"               varchar(255) not null,
    "PatientEmergencyContactId" integer
        constraint "patient_PatientEmergencyContact_foreign"
            references "PatientEmergencyContact",
    "PatientStatusId"           integer      not null
        constraint "patient_PatientStatus_foreign"
            references "PatientStatus",
    "RegistrationDate"          timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedDate"               timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"                 integer
        constraint "Patient_accounts_id_foreign"
            references "Accounts",
    "IsActive"                  boolean,
    "ModifiedDate"              timestamp with time zone default CURRENT_TIMESTAMP,
    "SoundX"                    varchar
);

alter table "PatientList"
    owner to postgres;

create table "Doc_Dashboard"
(
    id                       integer generated by default as identity
        constraint "Doc_Dashboard_pkey"
            primary key,
    "PatientId"              integer not null
        constraint doc_dashboard_patient_foreign
            references "PatientList",
    "HistoryId"              integer
        constraint doc_dashboard_history_foreign
            references "PatientHistory",
    "VitalSignsId"           integer
        constraint doc_dashboard_vital_signs_foreign
            references "VitalSigns",
    "PhysicalExaminationsId" integer
        constraint doc_dashboard_physical_examinations_foreign
            references "PhysicalExamination",
    "DiagnosisId"            integer
        constraint doc_dashboard_diagnosislist_id_fk
            references "DiagnosisList",
    "ProgressId"             integer
        constraint doc_dashboard_progress_foreign
            references "PatientProgress",
    "ManagementId"           integer
        constraint doc_dashboard_management_foreign
            references "PatientManagement",
    "CreatedDate"            timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"              integer
        constraint "Doc_Dashboard_accounts_id_foreign"
            references "Accounts",
    "IsActive"               boolean,
    "ModifiedDate"           timestamp with time zone default CURRENT_TIMESTAMP,
    clinic                   integer
        constraint doc_dashboard_cliniclist_id_fk
            references "ClinicList"
);

alter table "Doc_Dashboard"
    owner to postgres;

create table "Invoice"
(
    id             integer generated by default as identity
        constraint "Invoice_pkey"
            primary key,
    "PatientId"    integer not null
        constraint invoice_patient_foreign
            references "PatientList",
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "Invoice_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Invoice"
    owner to postgres;

create table "PatientPrescription"
(
    id                integer generated by default as identity
        constraint "PatientPrescription_pkey"
            primary key,
    "Medication"      varchar(255),
    "Strength"        varchar,
    "AmountToBeTaken" varchar,
    "Frequency"       varchar(255),
    "Route"           varchar(255) not null,
    "HowMuch"         varchar(255),
    "Refills"         varchar(255) not null,
    "Note"            varchar(255),
    "CreatedDate"     timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"       integer
        constraint "PatientPrescription_accounts_id_foreign"
            references "Accounts",
    "IsActive"        boolean,
    "ModifiedDate"    timestamp with time zone default CURRENT_TIMESTAMP,
    "PatientId"       integer
        constraint patientprescription_patientlist_id_fk
            references "PatientList",
    "Clinic"          integer
        constraint patientprescription_cliniclist_id_fk
            references "ClinicList"
);

alter table "PatientPrescription"
    owner to postgres;

create table "RadRequestResult"
(
    id             integer generated by default as identity
        constraint "RadRequestResult_pkey"
            primary key,
    "PatientId"    integer not null
        constraint "RadRequestResult_Patient_id_foreign"
            references "PatientList",
    "Result"       varchar,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"    integer
        constraint "RadRequestResult_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP,
    "Clinic"       integer
        constraint radrequestresult_cliniclist_id_fk
            references "ClinicList"
);

alter table "RadRequestResult"
    owner to postgres;

create table "OrderedImageRequestInfo"
(
    id                      serial not null
        constraint orderedimagerequestinfo_pk
            primary key,
    "AdditionalInformation" varchar,
    "CreatedBy"             integer
        constraint orderedimagerequestinfo_accounts_id_fk
            references "Accounts",
    "CreatedDate"           timestamp with time zone default CURRENT_TIMESTAMP,
    "PatientId"             integer
        constraint orderedimagerequestinfo_patientlist_id_fk
            references "PatientList"
);

alter table "OrderedImageRequestInfo"
    owner to postgres;

create unique index orderedimagerequestinfo_id_uindex
    on "OrderedImageRequestInfo" (id);

create table "Manufacturer"
(
    "Id"                  serial                                 not null
        constraint manufacturer_pk
            primary key,
    "Name"                varchar                                not null,
    "Abbreviation"        varchar                                not null,
    isin                  varchar,
    "HeadQuarterLocation" varchar,
    "Website"             varchar,
    "CreatedBy"           integer
        constraint manufacturer_accounts_id_fk
            references "Accounts",
    "IsActive"            boolean,
    "CreatedDate"         timestamp(3) default CURRENT_TIMESTAMP not null,
    "ModifiedDate"        timestamp(3)
);

alter table "Manufacturer"
    owner to postgres;

create table "Product"
(
    id                    integer generated by default as identity
        constraint "Product_pkey"
            primary key
        constraint product_manufacturer_id_fk
            references "Manufacturer"
        constraint product_unitofmeasurement_id_fk
            references "UnitOfMeasurements",
    "Name"                varchar(255) not null,
    "Code"                varchar(255) not null,
    "Amount"              integer      not null,
    "UnitOfMeasurementid" integer      not null,
    "DosageForm"          varchar(255) not null,
    "Manufacturer"        integer      not null,
    "CreatedDate"         timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"           integer
        constraint "Product_accounts_id_foreign"
            references "Accounts",
    "IsActive"            boolean,
    "ModifiedDate"        timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Product"
    owner to postgres;

create table "Stock"
(
    id                   integer generated by default as identity
        constraint "Stock_pkey"
            primary key,
    "ProductId"          integer          not null
        constraint stock_productid_foreign
            references "Product",
    "ReferralID"         varchar(255)     not null,
    "BatchId"            varchar(255)     not null,
    "TotalUnitPurchased" double precision not null,
    "UnitPurchasedPrice" double precision not null,
    "UnitRetailPrice"    double precision not null,
    "ManufactureDate"    date             not null,
    "IsExpireId"         integer          not null
        constraint stock_is_expire_foreign
            references "IsExpire",
    "RemainsUnit"        integer          not null,
    "CreatedDate"        timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"          integer
        constraint "Stock_accounts_id_foreign"
            references "Accounts",
    "IsActive"           boolean,
    "ModifiedDate"       timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "Stock"
    owner to postgres;

create table "InvoiceItem"
(
    id                      integer generated by default as identity
        constraint "InvoiceItem_pkey"
            primary key,
    "InvoiceId"             integer          not null
        constraint invoice_id_foreign
            references "Invoice",
    "StockId"               integer          not null
        constraint invoiceitem_stockid_foreign
            references "Stock",
    "OrderedQuantity"       double precision not null,
    "OrderedBy"             integer,
    "CreatedDate"           timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"             integer
        constraint "InvoiceItem_accounts_id_foreign"
            references "Accounts",
    "IsActive"              boolean,
    "ModifiedDate"          timestamp with time zone default CURRENT_TIMESTAMP,
    "PatientPrescriptionId" integer
        constraint invoiceitem_patientprescription_id_fk
            references "PatientPrescription"
);

alter table "InvoiceItem"
    owner to postgres;

create table "InvoiceItemStatus"
(
    id              integer generated by default as identity
        constraint "InvoiceItemStatus_pkey"
            primary key,
    "InvoiceItemId" integer
        constraint invoiceitemstatus_invoiceitem_id_fk
            references "InvoiceItem",
    "InvoiceNumber" varchar(255) not null,
    "CreatedDate"   timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"     integer
        constraint "InvoiceItemStatus_accounts_id_foreign"
            references "Accounts",
    "IsActive"      boolean,
    "ModifiedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "paidAmount"    double precision
);

alter table "InvoiceItemStatus"
    owner to postgres;

create unique index manufacturer_id_uindex
    on "Manufacturer" ("Id");

create table "OrderedLabPanelInfo"
(
    id                      serial not null
        constraint orderedlabpanelinfo_pk
            primary key,
    "PatientId"             integer
        constraint orderedlabpanelinfo_patientlist_id_fk
            references "PatientList",
    "AdditionalInformation" varchar,
    "CreatedBy"             integer
        constraint orderedlabpanelinfo_accounts_id_fk
            references "Accounts",
    "CreatedDate"           timestamp default CURRENT_TIMESTAMP,
    "Clinic"                integer
        constraint orderedlabpanelinfo_cliniclist_id_fk
            references "ClinicList"
);

alter table "OrderedLabPanelInfo"
    owner to postgres;

create table "LabTestResult"
(
    id               integer generated by default as identity
        constraint "LabTestResult_pkey"
            primary key,
    "infoId"         integer not null
        constraint "LabTestResult_info_foreign"
            references "OrderedLabPanelInfo",
    "orderedPanelId" integer not null
        constraint "LabTestResult_ordered_id_foreign"
            references "LabPanels",
    "testId"         integer not null
        constraint "LabTestResult_test_id_foreign"
            references "LabTests",
    result           varchar(255),
    "createdDate"    timestamp with time zone default CURRENT_TIMESTAMP,
    "createdBy"      integer
        constraint "LabTestResult_accounts_id_foreign"
            references "Accounts",
    "isActive"       boolean,
    "modifiedDate"   timestamp with time zone default CURRENT_TIMESTAMP
);

alter table "LabTestResult"
    owner to postgres;

create unique index orderedlabpanelinfo_id_uindex
    on "OrderedLabPanelInfo" (id);

create table "PaymentType"
(
    id     serial not null
        constraint paymenttype_pk
            primary key,
    "Name" varchar
);

alter table "PaymentType"
    owner to postgres;

create table "PaymentStatus"
(
    id             integer generated by default as identity
        constraint "PaymentStatus_pkey"
            primary key,
    "isPayed"      boolean      not null,
    "Remark"       varchar(255) not null,
    "CreatedDate"  timestamp with time zone default CURRENT_TIMESTAMP,
    "ApprovedBy"   integer
        constraint "PaymentStatus_accounts_id_foreign"
            references "Accounts",
    "IsActive"     boolean,
    "ModifiedDate" timestamp with time zone default CURRENT_TIMESTAMP,
    "Type"         integer
        constraint paymentstatus_paymenttype_id_fk
            references "PaymentType",
    "paidAmount"   double precision
);

alter table "PaymentStatus"
    owner to postgres;

create table "OrderedImagRequest"
(
    id                integer generated by default as identity
        constraint "OrderedImagRequest_pkey"
            primary key,
    "InfoId"          integer
        constraint orderedimagrequest_orderedimagerequestinfo_id_fk
            references "OrderedImageRequestInfo",
    "RequestId"       integer not null
        constraint "orderedimagrequest_Request_id_foreign"
            references "RadRequest",
    "TransferRadId"   integer not null
        constraint "orderedimagrequest_TransferRad_id_foreign"
            references "RadTransferStatus",
    "PaymentStatusId" integer not null
        constraint orderedimagrequest_paymentstatusid_foreign
            references "PaymentStatus",
    "CreatedDate"     timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"       integer
        constraint "OrderedImagRequest_accounts_id_foreign"
            references "Accounts",
    "IsActive"        boolean,
    "ModifiedDate"    timestamp with time zone default CURRENT_TIMESTAMP,
    "ResultId"        integer
        constraint orderedimagrequest_radrequestresult_id_fk
            references "RadRequestResult",
    "Clinic"          integer
        constraint orderedimagrequest_cliniclist_id_fk
            references "ClinicList"
);

alter table "OrderedImagRequest"
    owner to postgres;

create table "OrderedLabPanel"
(
    id                integer generated by default as identity
        constraint "OrderedLabPanel_pkey"
            primary key,
    "InfoId"          integer
        constraint orderedpanel_patient_foreign
            references "OrderedLabPanelInfo",
    "PanelId"         integer not null
        constraint orderedpanel_panel_id_foreign
            references "LabPanels",
    "TransferLabId"   integer not null
        constraint "orderedpanel_TransferLab_foreign"
            references "LabTransferStatus",
    "PaymentStatusId" integer not null
        constraint orderedpanel_paymentstatusid_foreign
            references "PaymentStatus",
    "CreatedDate"     timestamp with time zone default CURRENT_TIMESTAMP,
    "CreatedBy"       integer
        constraint "OrderedLabPanel_accounts_id_foreign"
            references "Accounts",
    "IsActive"        boolean,
    "ModifiedDate"    timestamp with time zone default CURRENT_TIMESTAMP,
    "Clinic"          integer
        constraint orderedlabpanel_cliniclist_id_fk
            references "ClinicList"
);

alter table "OrderedLabPanel"
    owner to postgres;

create unique index paymenttype_id_uindex
    on "PaymentType" (id);

